-- Canonical subtype taxonomy — single source of truth for entity_subtype values.
--
-- Problem this fixes: entity_subtype was free text with no validation, leading
-- to duplicate spellings of the same concept (e.g. "beauty_salon" vs
-- "beauty-salon", "fishing_charter" vs "charter-fishing") scattered across the
-- entity table, and three separate hardcoded JS mappings (categoryMap.js,
-- listing-category-map.js, GCRCard.jsx's ACTIVITY_SUBTYPES) that could
-- silently disagree with each other and with the live data.
--
-- This table is descriptive/reference data seeded from the live entity table
-- as of this migration (293 distinct normalized subtypes, covering 2734
-- entities) cross-referenced against the existing categoryMap.js mapping.
-- It is NOT yet wired into any live query path — routes/gcr.js and the
-- frontend's categoryMap.js/listing-category-map.js still do their own
-- lookups. Wiring those to read from this table instead of duplicating the
-- mapping is a follow-up step.

CREATE TABLE IF NOT EXISTS subtype_taxonomy (
  id uuid primary key default gen_random_uuid(),
  subtype_key text unique not null,
  display_name text not null,
  entity_type text not null,
  listing_category text not null,
  entity_count integer not null default 0,
  created_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_subtype_taxonomy_category ON subtype_taxonomy(listing_category);
CREATE INDEX IF NOT EXISTS idx_subtype_taxonomy_entity_type ON subtype_taxonomy(entity_type);

INSERT INTO subtype_taxonomy (subtype_key, display_name, entity_type, listing_category, entity_count) VALUES
('service', 'Service', 'service', 'services', 145),
('restaurant', 'Restaurant', 'restaurant', 'restaurants', 135),
('travel_agency', 'Travel Agency', 'activity', 'services', 99),
('fishing_charter', 'Fishing Charter', 'activity', 'things-to-do', 97),
('store', 'Store', 'shopping', 'shopping', 76),
('seafood_restaurant', 'Seafood Restaurant', 'restaurant', 'restaurants', 70),
('tour_agency', 'Tour Agency', 'activity', 'things-to-do', 67),
('condominium_complex', 'Condominium Complex', 'condo', 'staying', 65),
('lodging', 'Lodging', 'service', 'staying', 59),
('hotel', 'Hotel', 'hotel', 'staying', 58),
('park', 'Park', 'park', 'public-spots', 48),
('clothing_store', 'Clothing Store', 'shopping', 'shopping', 48),
('hair_salon', 'Hair Salon', 'service', 'wellness', 34),
('condo', 'Condo', 'condo', 'staying', 33),
('shopping_mall', 'Shopping Mall', 'shopping', 'shopping', 33),
('rv_park', 'Rv Park', 'vacation-rental', 'staying', 33),
('marina', 'Marina', 'activity', 'things-to-do', 31),
('storage', 'Storage', 'service', 'services', 30),
('spa', 'Spa', 'service', 'wellness', 29),
('coffee_shop', 'Coffee Shop', 'coffee', 'coffee', 27),
('real_estate_agency', 'Real Estate Agency', 'service', 'services', 27),
('nail_salon', 'Nail Salon', 'service', 'wellness', 27),
('parking_lot', 'Parking Lot', 'service', 'services', 26),
('bar', 'Bar', 'restaurant', 'restaurants', 26),
('jewelry_store', 'Jewelry Store', 'shopping', 'shopping', 26),
('liquor_store', 'Liquor Store', 'shopping', 'shopping', 26),
('gym', 'Gym', 'activity', 'wellness', 25),
('ice_cream_shop', 'Ice Cream Shop', 'coffee', 'coffee', 23),
('resort_hotel', 'Resort Hotel', 'hotel', 'staying', 23),
('chinese_restaurant', 'Chinese Restaurant', 'restaurant', 'restaurants', 22),
('rentals', 'Rentals', 'service', 'things-to-do', 21),
('museum', 'Museum', 'park', 'public-spots', 21),
('beauty_salon', 'Beauty Salon', 'service', 'wellness', 21),
('gift_shop', 'Gift Shop', 'shopping', 'shopping', 21),
('veterinary_care', 'Veterinary Care', 'service', 'services', 20),
('book_store', 'Book Store', 'shopping', 'shopping', 20),
('womens_clothing_store', 'Womens Clothing Store', 'shopping', 'shopping', 20),
('tourist_attraction', 'Tourist Attraction', 'activity', 'things-to-do', 19),
('bakery', 'Bakery', 'coffee', 'coffee', 19),
('shoe_store', 'Shoe Store', 'shopping', 'shopping', 19),
('art_gallery', 'Art Gallery', 'shopping', 'shopping', 19),
('event_venue', 'Event Venue', 'restaurant', 'things-to-do', 18),
('massage', 'Massage', 'service', 'wellness', 18),
('american_restaurant', 'American Restaurant', 'restaurant', 'restaurants', 17),
('car_rental', 'Car Rental', 'service', 'services', 16),
('bar_and_grill', 'Bar And Grill', 'restaurant', 'restaurants', 16),
('pizza_restaurant', 'Pizza Restaurant', 'restaurant', 'restaurants', 16),
('mexican_restaurant', 'Mexican Restaurant', 'restaurant', 'restaurants', 16),
('bicycle_store', 'Bicycle Store', 'shopping', 'shopping', 16),
('golf_course', 'Golf Course', 'activity', 'things-to-do', 15),
('hiking_area', 'Hiking Area', 'activity', 'things-to-do', 14),
('sports_school', 'Sports School', 'activity', 'things-to-do', 14),
('boat_rental', 'Boat Rental', 'activity', 'things-to-do', 14),
('attraction', 'Attraction', 'activity', 'things-to-do', 14),
('state_park', 'State Park', 'park', 'public-spots', 14),
('bank', 'Bank', 'service', 'services', 14),
('vacation_rental', 'Vacation Rental', 'vacation-rental', 'staying', 14),
('dolphin_cruise', 'Dolphin Cruise', 'activity', 'things-to-do', 13),
('japanese_restaurant', 'Japanese Restaurant', 'restaurant', 'restaurants', 12),
('pet_store', 'Pet Store', 'shopping', 'shopping', 12),
('market', 'Market', 'shopping', 'shopping', 12),
('apartment_complex', 'Apartment Complex', 'condo', 'staying', 11),
('bed_and_breakfast', 'Bed And Breakfast', 'hotel', 'staying', 11),
('apartment_building', 'Apartment Building', 'service', 'staying', 11),
('health', 'Health', 'service', 'services', 11),
('sporting_goods_store', 'Sporting Goods Store', 'shopping', 'shopping', 11),
('campground', 'Campground', 'activity', 'staying', 10),
('performing_arts_theater', 'Performing Arts Theater', 'activity', 'things-to-do', 10),
('car_repair', 'Car Repair', 'service', 'services', 10),
('fitness_center', 'Fitness Center', 'service', 'wellness', 10),
('nature_preserve', 'Nature Preserve', 'activity', 'things-to-do', 9),
('amusement_center', 'Amusement Center', 'activity', 'things-to-do', 9),
('beach', 'Beach', 'park', 'public-spots', 9),
('thai_restaurant', 'Thai Restaurant', 'restaurant', 'restaurants', 9),
('supplier', 'Supplier', 'service', 'services', 9),
('yoga_studio', 'Yoga Studio', 'service', 'wellness', 9),
('association_or_organization', 'Association Or Organization', 'service', 'services', 9),
('laundry', 'Laundry', 'service', 'services', 9),
('grocery_store', 'Grocery Store', 'shopping', 'shopping', 9),
('jet_ski', 'Jet Ski', 'activity', 'things-to-do', 8),
('swimming_pool', 'Swimming Pool', 'activity', 'things-to-do', 8),
('miniature_golf_course', 'Miniature Golf Course', 'activity', 'things-to-do', 8),
('car_wash', 'Car Wash', 'service', 'services', 8),
('transportation_service', 'Transportation Service', 'service', 'services', 8),
('pharmacy', 'Pharmacy', 'shopping', 'shopping', 8),
('boat_tour', 'Boat Tour', 'activity', 'things-to-do', 7),
('sports_complex', 'Sports Complex', 'activity', 'things-to-do', 7),
('movie_theater', 'Movie Theater', 'activity', 'things-to-do', 7),
('amusement_park', 'Amusement Park', 'activity', 'things-to-do', 7),
('breakfast_restaurant', 'Breakfast Restaurant', 'restaurant', 'restaurants', 7),
('cafe', 'Cafe', 'restaurant', 'coffee', 7),
('italian_restaurant', 'Italian Restaurant', 'restaurant', 'restaurants', 7),
('hamburger_restaurant', 'Hamburger Restaurant', 'restaurant', 'restaurants', 7),
('consultant', 'Consultant', 'service', 'services', 7),
('wellness_center', 'Wellness Center', 'service', 'wellness', 7),
('barber_shop', 'Barber Shop', 'service', 'wellness', 7),
('gas_station', 'Gas Station', 'service', 'shopping', 7),
('farmers_market', 'Farmers Market', 'shopping', 'shopping', 7),
('bowling_alley', 'Bowling Alley', 'activity', 'things-to-do', 6),
('sports_club', 'Sports Club', 'activity', 'things-to-do', 6),
('motel', 'Motel', 'hotel', 'staying', 6),
('financial_services', 'Financial Services', 'hotel', 'services', 6),
('historical_landmark', 'Historical Landmark', 'park', 'public-spots', 6),
('brewery', 'Brewery', 'restaurant', 'nightlife', 6),
('sandwich_shop', 'Sandwich Shop', 'restaurant', 'restaurants', 6),
('convenience_store', 'Convenience Store', 'shopping', 'shopping', 6),
('florist', 'Florist', 'shopping', 'shopping', 6),
('retail', 'Retail', 'shopping', 'shopping', 6),
('furniture_store', 'Furniture Store', 'shopping', 'shopping', 6),
('parasailing', 'Parasailing', 'activity', 'things-to-do', 5),
('sports_activity_location', 'Sports Activity Location', 'activity', 'things-to-do', 5),
('video_arcade', 'Video Arcade', 'activity', 'things-to-do', 5),
('shopping', 'Shopping', 'shopping', 'shopping', 5),
('donut_shop', 'Donut Shop', 'coffee', 'coffee', 5),
('resort', 'Resort', 'hotel', 'staying', 5),
('dog_park', 'Dog Park', 'park', 'public-spots', 5),
('tourist_information_center', 'Tourist Information Center', 'park', 'public-spots', 5),
('indian_restaurant', 'Indian Restaurant', 'restaurant', 'restaurants', 5),
('brunch_restaurant', 'Brunch Restaurant', 'restaurant', 'restaurants', 5),
('entertainment', 'Entertainment', 'service', 'things-to-do', 5),
('general_contractor', 'General Contractor', 'service', 'services', 5),
('massage_spa', 'Massage Spa', 'service', 'wellness', 5),
('home_goods_store', 'Home Goods Store', 'shopping', 'shopping', 5),
('fishing_pier', 'Fishing Pier', 'activity', 'things-to-do', 4),
('zoo', 'Zoo', 'activity', 'things-to-do', 4),
('dessert_shop', 'Dessert Shop', 'coffee', 'coffee', 4),
('guest_house', 'Guest House', 'hotel', 'staying', 4),
('visitor_center', 'Visitor Center', 'park', 'public-spots', 4),
('steak_house', 'Steak House', 'restaurant', 'restaurants', 4),
('barbecue_restaurant', 'Barbecue Restaurant', 'restaurant', 'restaurants', 4),
('meal_takeaway', 'Meal Takeaway', 'restaurant', 'restaurants', 4),
('irish_pub', 'Irish Pub', 'restaurant', 'restaurants', 4),
('sports_bar', 'Sports Bar', 'restaurant', 'nightlife', 4),
('doctor', 'Doctor', 'service', 'services', 4),
('agency', 'Agency', 'service', 'services', 4),
('medical_clinic', 'Medical Clinic', 'service', 'services', 4),
('finance', 'Finance', 'service', 'services', 4),
('premise', 'Premise', 'service', 'services', 4),
('manufacturer', 'Manufacturer', 'service', 'services', 4),
('corporate_office', 'Corporate Office', 'service', 'services', 4),
('food_store', 'Food Store', 'shopping', 'shopping', 4),
('kayak_rental', 'Kayak Rental', 'activity', 'things-to-do', 3),
('bar_grill', 'Bar Grill', 'restaurant', 'restaurants', 3),
('live_music_venue', 'Live Music Venue', 'restaurant', 'nightlife', 3),
('night_club', 'Night Club', 'restaurant', 'nightlife', 3),
('winery', 'Winery', 'service', 'nightlife', 3),
('taxi_service', 'Taxi Service', 'service', 'services', 3),
('catering_service', 'Catering Service', 'service', 'services', 3),
('local_government_office', 'Local Government Office', 'service', 'services', 3),
('farm', 'Farm', 'service', 'services', 3),
('private_guest_room', 'Private Guest Room', 'service', 'services', 3),
('educational_institution', 'Educational Institution', 'service', 'services', 3),
('asian_restaurant', 'Asian Restaurant', 'service', 'services', 3),
('thrift_store', 'Thrift Store', 'shopping', 'shopping', 3),
('department_store', 'Department Store', 'shopping', 'shopping', 3),
('building_materials_store', 'Building Materials Store', 'shopping', 'shopping', 3),
('banana_boat', 'Banana Boat', 'activity', 'things-to-do', 2),
('watersports', 'Watersports', 'activity', 'things-to-do', 2),
('amphitheatre', 'Amphitheatre', 'activity', 'things-to-do', 2),
('sailing_charter', 'Sailing Charter', 'activity', 'things-to-do', 2),
('observation_deck', 'Observation Deck', 'activity', 'things-to-do', 2),
('parking', 'Parking', 'activity', 'services', 2),
('sunset_cruise', 'Sunset Cruise', 'activity', 'things-to-do', 2),
('helicopter_tour', 'Helicopter Tour', 'activity', 'things-to-do', 2),
('tour_operator', 'Tour Operator', 'activity', 'things-to-do', 2),
('cottage', 'Cottage', 'hotel', 'staying', 2),
('playground', 'Playground', 'park', 'public-spots', 2),
('pub', 'Pub', 'restaurant', 'restaurants', 2),
('fast_food_restaurant', 'Fast Food Restaurant', 'restaurant', 'restaurants', 2),
('takeout', 'Takeout', 'restaurant', 'restaurants', 2),
('oyster_bar_restaurant', 'Oyster Bar Restaurant', 'restaurant', 'restaurants', 2),
('diner', 'Diner', 'restaurant', 'restaurants', 2),
('cocktail_bar', 'Cocktail Bar', 'restaurant', 'restaurants', 2),
('chicken_restaurant', 'Chicken Restaurant', 'restaurant', 'restaurants', 2),
('pizza_delivery', 'Pizza Delivery', 'restaurant', 'restaurants', 2),
('lounge_bar', 'Lounge Bar', 'restaurant', 'nightlife', 2),
('hot_dog_restaurant', 'Hot Dog Restaurant', 'restaurant', 'restaurants', 2),
('community_center', 'Community Center', 'service', 'services', 2),
('real_estate', 'Real Estate', 'service', 'services', 2),
('tanning_studio', 'Tanning Studio', 'service', 'services', 2),
('non_profit_organization', 'Non Profit Organization', 'service', 'services', 2),
('wedding_venue', 'Wedding Venue', 'service', 'services', 2),
('airport_shuttle_service', 'Airport Shuttle Service', 'service', 'services', 2),
('bridge', 'Bridge', 'service', 'services', 2),
('aquarium', 'Aquarium', 'service', 'things-to-do', 2),
('body_art_service', 'Body Art Service', 'service', 'services', 2),
('chiropractor', 'Chiropractor', 'service', 'services', 2),
('lawyer', 'Lawyer', 'service', 'services', 2),
('unknown', 'Unknown', 'service', 'services', 2),
('salon', 'Salon', 'service', 'wellness', 2),
('tire_shop', 'Tire Shop', 'service', 'services', 2),
('chauffeur_service', 'Chauffeur Service', 'service', 'services', 2),
('point_of_interest', 'Point Of Interest', 'service', 'services', 2),
('toy_store', 'Toy Store', 'service', 'shopping', 2),
('artist', 'Artist', 'service', 'services', 2),
('garden_center', 'Garden Center', 'shopping', 'shopping', 2),
('supermarket', 'Supermarket', 'shopping', 'shopping', 2),
('flea_market', 'Flea Market', 'shopping', 'shopping', 2),
('cell_phone_store', 'Cell Phone Store', 'shopping', 'shopping', 2),
('asian_grocery_store', 'Asian Grocery Store', 'shopping', 'shopping', 2),
('hardware_store', 'Hardware Store', 'shopping', 'shopping', 2),
('sportswear_store', 'Sportswear Store', 'shopping', 'shopping', 2),
('adventure_sports_center', 'Adventure Sports Center', 'activity', 'things-to-do', 1),
('heliport', 'Heliport', 'activity', 'things-to-do', 1),
('scenic_spot', 'Scenic Spot', 'activity', 'things-to-do', 1),
('wildlife_refuge', 'Wildlife Refuge', 'activity', 'things-to-do', 1),
('performing_arts', 'Performing Arts', 'activity', 'things-to-do', 1),
('equipment_rental', 'Equipment Rental', 'activity', 'things-to-do', 1),
('bike_rental', 'Bike Rental', 'activity', 'things-to-do', 1),
('go_kart', 'Go Kart', 'activity', 'things-to-do', 1),
('tourism_destination', 'Tourism Destination', 'activity', 'things-to-do', 1),
('park_facility_rental', 'Park Facility Rental', 'activity', 'things-to-do', 1),
('ferris_wheel', 'Ferris Wheel', 'activity', 'things-to-do', 1),
('juice_shop', 'Juice Shop', 'coffee', 'coffee', 1),
('chocolate_shop', 'Chocolate Shop', 'coffee', 'coffee', 1),
('extended_stay_hotel', 'Extended Stay Hotel', 'hotel', 'staying', 1),
('vacation_rentals', 'Vacation Rentals', 'hotel', 'staying', 1),
('condominium_association', 'Condominium Association', 'hotel', 'staying', 1),
('vacation_rental_resort', 'Vacation Rental Resort', 'hotel', 'staying', 1),
('hotel_chain', 'Hotel Chain', 'hotel', 'staying', 1),
('cultural_landmark', 'Cultural Landmark', 'park', 'public-spots', 1),
('wildlife_park', 'Wildlife Park', 'park', 'public-spots', 1),
('historical_place', 'Historical Place', 'park', 'things-to-do', 1),
('sushi_restaurant', 'Sushi Restaurant', 'restaurant', 'restaurants', 1),
('wine_bar', 'Wine Bar', 'restaurant', 'nightlife', 1),
('mediterranean_restaurant', 'Mediterranean Restaurant', 'restaurant', 'restaurants', 1),
('meal_delivery', 'Meal Delivery', 'restaurant', 'restaurants', 1),
('taco_restaurant', 'Taco Restaurant', 'restaurant', 'restaurants', 1),
('tiki_bar', 'Tiki Bar', 'restaurant', 'restaurants', 1),
('greek_restaurant', 'Greek Restaurant', 'restaurant', 'restaurants', 1),
('tex_mex_restaurant', 'Tex Mex Restaurant', 'restaurant', 'restaurants', 1),
('food', 'Food', 'restaurant', 'restaurants', 1),
('wings_restaurant', 'Wings Restaurant', 'restaurant', 'restaurants', 1),
('deli', 'Deli', 'restaurant', 'restaurants', 1),
('government_office', 'Government Office', 'service', 'services', 1),
('discount_supermarket', 'Discount Supermarket', 'service', 'services', 1),
('bus_stop', 'Bus Stop', 'service', 'services', 1),
('family_restaurant', 'Family Restaurant', 'service', 'services', 1),
('airport', 'Airport', 'service', 'services', 1),
('vacation_rental_agency', 'Vacation Rental Agency', 'service', 'services', 1),
('indoor_playground', 'Indoor Playground', 'service', 'services', 1),
('drugstore', 'Drugstore', 'service', 'shopping', 1),
('skateboard_park', 'Skateboard Park', 'service', 'services', 1),
('banquet_hall', 'Banquet Hall', 'service', 'services', 1),
('confectionery', 'Confectionery', 'service', 'coffee', 1),
('pet_care', 'Pet Care', 'service', 'services', 1),
('garden', 'Garden', 'service', 'services', 1),
('stadium', 'Stadium', 'service', 'services', 1),
('software', 'Software', 'service', 'services', 1),
('skin_care_clinic', 'Skin Care Clinic', 'service', 'wellness', 1),
('title_company', 'Title Company', 'service', 'services', 1),
('financial', 'Financial', 'service', 'services', 1),
('parking_garage', 'Parking Garage', 'service', 'services', 1),
('korean_barbecue_restaurant', 'Korean Barbecue Restaurant', 'service', 'services', 1),
('salon_spa', 'Salon Spa', 'service', 'wellness', 1),
('water_park', 'Water Park', 'service', 'things-to-do', 1),
('cinema', 'Cinema', 'service', 'things-to-do', 1),
('boat_launch', 'Boat Launch', 'service', 'things-to-do', 1),
('vineyard', 'Vineyard', 'service', 'nightlife', 1),
('real_estate_agent', 'Real Estate Agent', 'service', 'services', 1),
('courier_service', 'Courier Service', 'service', 'services', 1),
('medical_center', 'Medical Center', 'service', 'services', 1),
('online_gambling', 'Online Gambling', 'service', 'services', 1),
('sports_coaching', 'Sports Coaching', 'service', 'services', 1),
('vietnamese_restaurant', 'Vietnamese Restaurant', 'service', 'services', 1),
('postal_service', 'Postal Service', 'service', 'services', 1),
('dentist', 'Dentist', 'service', 'services', 1),
('cleaning_service', 'Cleaning Service', 'service', 'services', 1),
('beauty_wellness', 'Beauty Wellness', 'service', 'wellness', 1),
('post_office', 'Post Office', 'service', 'services', 1),
('medical', 'Medical', 'service', 'services', 1),
('laundromat', 'Laundromat', 'service', 'services', 1),
('church', 'Church', 'service', 'services', 1),
('acai_shop', 'Acai Shop', 'service', 'services', 1),
('physiotherapist', 'Physiotherapist', 'service', 'services', 1),
('pet_boarding_service', 'Pet Boarding Service', 'service', 'services', 1),
('insurance_agency', 'Insurance Agency', 'service', 'services', 1),
('apartment_community', 'Apartment Community', 'service', 'services', 1),
('university', 'University', 'service', 'services', 1),
('go_karting_venue', 'Go Karting Venue', 'service', 'things-to-do', 1),
('soul_food_restaurant', 'Soul Food Restaurant', 'service', 'services', 1),
('software_platform', 'Software Platform', 'service', 'services', 1),
('mobile_home_park', 'Mobile Home Park', 'service', 'services', 1),
('health_food_store', 'Health Food Store', 'service', 'shopping', 1),
('beach_access', 'Beach Access', 'service', 'public-spots', 1),
('online_gaming', 'Online Gaming', 'service', 'services', 1),
('government', 'Government', 'service', 'services', 1),
('television_studio', 'Television Studio', 'service', 'services', 1),
('food_delivery', 'Food Delivery', 'service', 'services', 1),
('business_center', 'Business Center', 'service', 'services', 1),
('optician', 'Optician', 'shopping', 'shopping', 1),
('butcher_shop', 'Butcher Shop', 'shopping', 'shopping', 1),
('retail_liquor_store', 'Retail Liquor Store', 'shopping', 'shopping', 1)
ON CONFLICT (subtype_key) DO UPDATE SET entity_count = EXCLUDED.entity_count, entity_type = EXCLUDED.entity_type, listing_category = EXCLUDED.listing_category;
